title: Ruirui Zhang's Homepage
page-top-title: Ruirui Zhang
top-section-bg-text: Finance and Economics
home-subtitle: Ruirui Zhang&ensp;|&ensp;张瑞瑞
copyright-text: '&copy; Ruirui Zhang 2024-2025. All Rights Reserved.'
